services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
  mongodb:
    image: mongo
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: "rabbitmq:4-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: sarchiap1/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq #rabbitmq is the name of the service inside the docker-compose file
      - ConnectionStrings__DefaultConnection=Server=postgres:5432; User Id=postgres;Password=postgrespw;Database=auction #postgres is the name of the service inside the docker-compose file
      - IdentityServerUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: sarchiap1/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq #rabbitmq is the name of the service inside the docker-compose file
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb #mongodb is the name of the service inside the docker-compose file
      - AuctionServiceUrl=http://auction-svc #auction-svc is the name of the service inside the docker-compose file
    ports:
      - 7002:80
    depends_on:
      - postgres
      - rabbitmq
  identity-svc:
    image: sarchiap1/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432; User Id=postgres;Password=postgrespw;Database=identity #postgres is the name of the service inside the docker-compose file
    ports:
      - 5001:80
    depends_on:
      - postgres
  gateway-svc:
    image: sarchiap1/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
volumes:
  pgdata:
  mongodata: